### ISSUE TITLE
runtime error: index out of range [65533] with length 58363

### ISSUE THREAD

**Issue by IOrlandoni** [launchdarkly/find-code-references#45]
Every now and then we have a commit that breaks the action, which means that the refs don't get updated and the action continues to fail for the next 10 commits (due to the lookback), maybe missing some updates forever.

Here's the logs of the failure, slightly redacted.
```
DEBUG: 2023/10/25 20:19:57 client.go:599: [DEBUG] PUT https://app.launchdarkly.com/api/v2/code-refs/repositories/[REDACTED]/branches/main
INFO: 2023/10/25 20:19:58 coderefs.go:182: checking if 223 flags without references were removed in the last 10 commits for project: default
DEBUG: 2023/10/25 20:19:58 git.go:245: Examining commit: [REDACTED][170](https://github.com/[REDACTED])[REDACTED]
panic: runtime error: index out of range [65533] with length 58363

goroutine 1 [running]:
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc0009a48a8?, {0xc0002f4a20, 0xb, 0x11000?}, {0xc004000000, 0xe3fb, 0x11000?})
	/tmp/project-releaser/project/vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go:452 +0x29b
github.com/go-git/go-git/v5/utils/diff.DoWithTimeout({0xc0057a0000?, 0x1?}, {0xc00606c000?, 0x2?}, 0xc001a30e80?)
	/tmp/project-releaser/project/vendor/github.com/go-git/go-git/v5/utils/diff/diff.go:37 +0x11d
github.com/go-git/go-git/v5/utils/diff.Do(...)
	/tmp/project-releaser/project/vendor/github.com/go-git/go-git/v5/utils/diff/diff.go:22
github.com/go-git/go-git/v5/plumbing/object.filePatchWithContext({0xa0df18, 0xc00002e0b8}, 0xc001a30d80)
	/tmp/project-releaser/project/vendor/github.com/go-git/go-git/v5/plumbing/object/patch.go:68 +0x195
github.com/go-git/go-git/v5/plumbing/object.getPatchContext({0xa0df18, 0xc00002e0b8}, {0x0, 0x0}, {0xc001153c20, 0x3, 0x5?})
	/tmp/project-releaser/project/vendor/github.com/go-git/go-git/v5/plumbing/object/patch.go:38 +0xf4
github.com/go-git/go-git/v5/plumbing/object.Changes.PatchContext(...)
	/tmp/project-releaser/project/vendor/github.com/go-git/go-git/v5/plumbing/object/change.go:158
github.com/launchdarkly/ld-find-code-refs/v2/internal/git.Client.FindExtinctions({{0xc0000321c1, 0x11}, {0xc000030016, 0x4}, {0xc000033bc0, 0x28}, 0x18b43f11920}, {{0xc0000281a4, 0x7}, {0x0, ...}, ...}, ...)
	/tmp/project-releaser/project/internal/git/git.go:250 +0x3de
github.com/launchdarkly/ld-find-code-refs/v2/coderefs.runExtinctions({{0xc00002a090, 0x28}, {0xc00003203c, 0x1c}, {0xc000030016, 0x4}, {0x0, 0x0}, {0xc00002fe78, 0x4}, ...}, ...)
	/tmp/project-releaser/project/coderefs/coderefs.go:[183](https://github.com/benchsci/bsci/actions/runs/6645431980/job/18057601554#step:4:184) +0xa25
github.com/launchdarkly/ld-find-code-refs/v2/coderefs.Run({{0xc00002a090, 0x28}, {0xc00003203c, 0x1c}, {0xc000030016, 0x4}, {0x0, 0x0}, {0xc00002fe78, 0x4}, ...}, ...)
	/tmp/project-releaser/project/coderefs/coderefs.go:75 +0x9db
main.main()
	/tmp/project-releaser/project/build/package/github-actions/github-actions.go:25 +0x15d
```

**Comment by jazanne** [comment]
@IOrlandoni at the moment this is a known issue with one of our dependencies. you can track the issue here https://github.com/launchdarkly/ld-find-code-refs/issues/351

Sorry for the inconvenience
